### ISSUE TITLE
Hint: Using  "dev" mode  instead of "release" to ViteRsw without  full build problem

### ISSUE THREAD

**Issue by deftsp** [yuchanns/rustbyexample#1]
https://github.com/yuchanns/rustbyexample/blob/8f7ee36d394d6e29a0ae702695d3f14379570faa/crates/yew-tailwindcss/vite.config.ts#L7

Thanks to your example, it helps me a lot.

I tried to set the  ViteRsw mode to `dev`, it leads to a full build for every change. Because `cargo check` (or rust-analyzer) and `wasm-pack build --dev --target` have different target.

I guess it's the reason why you let it to `release`  mode. 

It can be solved by adding a  yew-tailwindcss/.cargo/config.toml.  
```
.cargo/config.toml
[build]
target = "wasm32-unknown-unknown"
```

**Comment by yuchanns** [comment]
Thank you
